version = 0.1
[default.deploy.parameters]
stack_name = "my-sam-app"
resolve_s3 = true
s3_prefix = "my-sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
parameter_overrides = "EnvType=\"dev\""
